repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json

-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: npm run lint
        language: system
        types: [javascript, jsx, ts, tsx]
        files: \.(js|jsx|ts|tsx)$

    -   id: prettier
        name: prettier
        entry: npm run format
        language: system
        types: [javascript, jsx, ts, tsx]
        files: \.(js|jsx|ts|tsx|css|md)$
